version: "3.1"

services:
  web:
    image: medqi/web
    volumes:
      - ./medqi_web:/app
    ports:
      - 3000:3000
    depends_on:
      - api
      - db

  api:
    image: medqi/api
    volumes:
      - ./medqi_api:/app
    networks:
      - backend
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: medqi
    ports:
      - 5435:5432
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  backend:

volumes:
  db_data:
